package com.tournament.api.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a participant species in the Galactic Tournament.
 * <p>
 * This class is mapped to the database and stores both the physical characteristics (power, ability) and the performance history (victories).
 * </p>
 *
 * @author Anthony Ortega
 * @version 1.0
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Entity representing a galactic species participating in the tournament")
public class Species {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Unique identifier auto-generated by the database", example = "1")
    private Long id;

    @NotBlank(message = "Name cannot be blank")
    @Column(unique = true)
    @Schema(description = "Unique name of the species", example = "Human", requiredMode = Schema.RequiredMode.REQUIRED)
    private String name;

    @Min(value = 1, message = "Power level must be greater than 0")
    @Schema(description = "Numerical power level for battle calculations", example = "85")
    private Integer powerLevel;

    @Schema(description = "Specific trait or skill of the species", example = "Super strength")
    private String specialAbility;

    @Schema(description = "Total number of battles won in the tournament", example = "5")
    private Integer victories = 0;
}
